apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespase }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ .Values.deployment.container.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.container.name }}
    spec:
      containers:
        - name: {{ .Values.deployment.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.deployment.container.port }}
          readinessProbe:
            httpGet:
              port: {{ .Values.deployment.container.port }}
              path: {{ .Values.deployment.container.healthcheckPath}}
            timeoutSeconds: {{ .Values.deployment.container.healthcheckTimeout }}
