apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.namespase }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: {{ .Values.ingress.annotations.rewrite_target }}
spec:
  rules:
    - host: {{ .Values.ingress.rules.host }}
      http:
        paths:
          - path: {{ .Values.ingress.rules.path }}
            backend:
              serviceName: {{ .Values.service.name }}
              servicePort: {{ .Values.ingress.rules.servicePort }}
