namespase: minikube-sample

image:
  repository: 127.0.0.1:5000/minikube-sample
  tag: v0.0.1
  pullPolicy: IfNotPresent

ingress:
  name: minikube-sample-ingress
  annotations:
    rewrite_target: /$1
  rules:
    host: minikube-sample.local
    path: /
    servicePort: 3000

service:
  name: minikube-sample-service
  type: NodePort
  port: 3000
  targetPort: 3000

deployment:
  name: minikube-sample
  container:
    name: minikube-sample
    port: 3000
    healthcheckTimeout: 10
    healthcheckPath: /
